// <auto-generated />
using System;
using MechanicHelper.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MechanicHelper.Migrations
{
    [DbContext(typeof(MechanicDbContext))]
    [Migration("20210222103617_AddedSeed")]
    partial class AddedSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MechanicHelper.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Built")
                        .HasColumnType("datetime2");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = -1,
                            Built = new DateTime(2021, 2, 22, 11, 36, 17, 316, DateTimeKind.Local).AddTicks(1298),
                            Distance = 20000,
                            Make = "Alfa",
                            Model = "Romeo"
                        },
                        new
                        {
                            CarId = -2,
                            Built = new DateTime(2021, 2, 22, 11, 36, 17, 318, DateTimeKind.Local).AddTicks(8851),
                            Distance = 20000,
                            Make = "Alfa",
                            Model = "Romeo"
                        },
                        new
                        {
                            CarId = -3,
                            Built = new DateTime(2021, 2, 22, 11, 36, 17, 318, DateTimeKind.Local).AddTicks(8882),
                            Distance = 20000,
                            Make = "Alfa",
                            Model = "Romeo"
                        });
                });

            modelBuilder.Entity("MechanicHelper.Models.Problem", b =>
                {
                    b.Property<int>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int>("ProblemOnId")
                        .HasColumnType("int");

                    b.HasKey("ProblemId");

                    b.HasIndex("ProblemOnId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("MechanicHelper.Models.RepairService", b =>
                {
                    b.Property<int>("RepairServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfRepair")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ServicedOnId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RepairServiceId");

                    b.HasIndex("ServicedOnId");

                    b.ToTable("RepairServices");
                });

            modelBuilder.Entity("MechanicHelper.Models.Problem", b =>
                {
                    b.HasOne("MechanicHelper.Models.Car", "ProblemOn")
                        .WithMany("Problems")
                        .HasForeignKey("ProblemOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemOn");
                });

            modelBuilder.Entity("MechanicHelper.Models.RepairService", b =>
                {
                    b.HasOne("MechanicHelper.Models.Car", "ServicedOn")
                        .WithMany("Repairs")
                        .HasForeignKey("ServicedOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicedOn");
                });

            modelBuilder.Entity("MechanicHelper.Models.Car", b =>
                {
                    b.Navigation("Problems");

                    b.Navigation("Repairs");
                });
#pragma warning restore 612, 618
        }
    }
}
